<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;

/**
 * Dumps the full schema + catalog data of a source DB (typically `nexfile`)
 * into two versioned SQL scripts:
 *
 *   DB/baseline/v1.0/schema.sql   ← CREATE TABLE / VIEW (with renames applied)
 *   DB/baseline/v1.0/data.sql     ← INSERT statements for catalog rows
 *
 * Transforms baked into schema.sql so the source DB stays untouched:
 *   - RENAME file_status → file_state
 *   - RENAME file_sub_status → file_sub_state
 *   - APPEND client_group + client_group_process + client_group_phase
 *   - APPEND company.id_client_group + file_state.requires_payment_voucher
 *
 * The WIZARD applies these scripts when provisioning a new tenant.
 *
 * Usage:
 *   php spark db:dump-baseline                          # source = default DB, version = 1.0
 *   php spark db:dump-baseline --source=nexfile --version=1.1
 */
class DumpBaselineCommand extends BaseCommand
{
    protected $group       = 'Tenant';
    protected $name        = 'db:dump-baseline';
    protected $description = 'Dump source DB schema + catalog data to DB/baseline/v<X>/{schema,data}.sql';
    protected $usage       = 'db:dump-baseline [--source=<db>] [--version=<v>]';
    protected $options     = [
        '--source'  => 'Source DB name (default: from .env)',
        '--version' => 'Baseline version label (default: 1.0)',
    ];

    /** table → renamed-table emitted to the script. */
    private const TABLE_RENAMES = [
        'file_status'     => 'file_state',
        'file_sub_status' => 'file_sub_state',
    ];

    /** Catalog tables whose rows go into data.sql. Order matters (FK deps).
     *  NOTE: tablas tenant-config (configuration_process,
     *  configuration_process_document_type, etc.) NO se incluyen — cada tenant
     *  arma su propia configuración. Solo van catálogos de referencia (roles,
     *  estados, tipos de documento, etc.). */
    private const CATALOG_TABLES = [
        'user_role',
        'process',
        'customer_type',
        'operation_type',
        'payment_method',
        'file_status',           // → file_state after rename
        'file_sub_status',       // → file_sub_state after rename
        'document_type',
        'file_reasons',
        'document_file_error',
        'document_file_status',
        'file_exception_reason',
    ];

    public function run(array $params)
    {
        $sourceDb = (string) (CLI::getOption('source') ?? '');
        $version  = (string) (CLI::getOption('version') ?? '1.0');
        if (!preg_match('/^\d+\.\d+(\.\d+)?$/', $version)) {
            CLI::error('--version must be like 1.0 or 1.0.1');
            return EXIT_ERROR;
        }

        $db = Database::connect();
        if ($sourceDb === '') $sourceDb = $db->getDatabase();
        if (!preg_match('/^[A-Za-z0-9_]+$/', $sourceDb)) {
            CLI::error('invalid --source');
            return EXIT_ERROR;
        }

        $outDir = ROOTPATH . '../DB/baseline/v' . $version;
        if (!is_dir($outDir)) @mkdir($outDir, 0775, true);
        $schemaFile = $outDir . '/schema.sql';
        $dataFile   = $outDir . '/data.sql';

        CLI::write("Source DB: {$sourceDb}", 'cyan');
        CLI::write("Version  : {$version}", 'cyan');
        CLI::write("Output   : {$outDir}/", 'cyan');
        CLI::newLine();

        // ===== SCHEMA =====
        $schemaSql = $this->buildSchemaSql($db, $sourceDb);
        file_put_contents($schemaFile, $schemaSql);
        $kb = round(strlen($schemaSql) / 1024, 1);
        CLI::write("+ schema.sql ({$kb} KB)", 'green');

        // ===== DATA =====
        $dataSql = $this->buildDataSql($db, $sourceDb);
        file_put_contents($dataFile, $dataSql);
        $kb = round(strlen($dataSql) / 1024, 1);
        CLI::write("+ data.sql ({$kb} KB)", 'green');

        return EXIT_SUCCESS;
    }

    private function buildSchemaSql($db, string $sourceDb): string
    {
        $out = "-- NexFile baseline schema dump\n";
        $out .= "-- Source: `{$sourceDb}` on " . date('Y-m-d H:i:s') . "\n";
        $out .= "-- Transformations applied:\n";
        $out .= "--   - file_status         → file_state\n";
        $out .= "--   - file_sub_status     → file_sub_state\n";
        $out .= "--   - + client_group, client_group_process, client_group_phase\n";
        $out .= "--   - + company.id_client_group\n";
        $out .= "--   - + file_state.requires_payment_voucher (id=2 backfilled in data.sql)\n";
        $out .= "-- Generated by: php spark db:dump-baseline\n\n";

        $out .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

        // Discover base tables vs views
        $rows = $db->query(
            "SELECT TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? ORDER BY TABLE_NAME",
            [$sourceDb]
        )->getResultArray();
        $baseTables = $views = [];
        foreach ($rows as $r) {
            if ($r['TABLE_TYPE'] === 'VIEW') $views[] = $r['TABLE_NAME'];
            else $baseTables[] = $r['TABLE_NAME'];
        }

        // === Base tables ===
        foreach ($baseTables as $t) {
            $renamed = self::TABLE_RENAMES[$t] ?? $t;
            $ddl = $db->query("SHOW CREATE TABLE `{$sourceDb}`.`{$t}`")->getRowArray()['Create Table'] ?? null;
            if (!$ddl) continue;

            // Apply the rename if this is a renamed table
            if ($renamed !== $t) {
                $ddl = preg_replace('/^CREATE TABLE `' . preg_quote($t, '/') . '`/', 'CREATE TABLE `' . $renamed . '`', $ddl, 1);
            }

            // Drop AUTO_INCREMENT=N counter (clean state for a new tenant)
            $ddl = preg_replace('/\s+AUTO_INCREMENT=\d+/', '', $ddl);

            $out .= "-- ------ Table: `{$renamed}`" . ($renamed !== $t ? " (renamed from `{$t}`)" : '') . " ------\n";
            $out .= "DROP TABLE IF EXISTS `{$renamed}`;\n";
            $out .= $ddl . ";\n\n";
        }

        // === Phase A additions ===
        $out .= "-- ====== Phase A additions ======\n\n";
        $out .= "-- client_group (top-level grouping above company)\n";
        $out .= "DROP TABLE IF EXISTS `client_group`;\n";
        $out .= "CREATE TABLE `client_group` (\n";
        $out .= "  `id` BIGINT NOT NULL AUTO_INCREMENT,\n";
        $out .= "  `name` VARCHAR(200) NOT NULL,\n";
        $out .= "  `description` TEXT NULL,\n";
        $out .= "  `enabled` TINYINT(1) NOT NULL DEFAULT 1,\n";
        $out .= "  `registration_date` DATETIME DEFAULT CURRENT_TIMESTAMP,\n";
        $out .= "  `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n";
        $out .= "  `id_last_user_update` BIGINT NULL,\n";
        $out .= "  PRIMARY KEY (`id`),\n";
        $out .= "  UNIQUE KEY `uq_client_group_name` (`name`)\n";
        $out .= ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n\n";

        $out .= "DROP TABLE IF EXISTS `client_group_process`;\n";
        $out .= "CREATE TABLE `client_group_process` (\n";
        $out .= "  `id` BIGINT NOT NULL AUTO_INCREMENT,\n";
        $out .= "  `id_client_group` BIGINT NOT NULL,\n";
        $out .= "  `id_process` BIGINT NOT NULL,\n";
        $out .= "  `display_order` INT DEFAULT 0,\n";
        $out .= "  `enabled` TINYINT(1) DEFAULT 1,\n";
        $out .= "  `registration_date` DATETIME DEFAULT CURRENT_TIMESTAMP,\n";
        $out .= "  `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n";
        $out .= "  PRIMARY KEY (`id`),\n";
        $out .= "  UNIQUE KEY `uq_cgp` (`id_client_group`, `id_process`),\n";
        $out .= "  CONSTRAINT `fk_cgp_client_group` FOREIGN KEY (`id_client_group`) REFERENCES `client_group` (`id`) ON DELETE CASCADE\n";
        $out .= ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n\n";

        $out .= "DROP TABLE IF EXISTS `client_group_phase`;\n";
        $out .= "CREATE TABLE `client_group_phase` (\n";
        $out .= "  `id` BIGINT NOT NULL AUTO_INCREMENT,\n";
        $out .= "  `id_client_group` BIGINT NOT NULL,\n";
        $out .= "  `id_file_state` BIGINT NOT NULL,\n";
        $out .= "  `display_order` INT DEFAULT 0,\n";
        $out .= "  `enabled` TINYINT(1) DEFAULT 1,\n";
        $out .= "  `registration_date` DATETIME DEFAULT CURRENT_TIMESTAMP,\n";
        $out .= "  `update_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n";
        $out .= "  PRIMARY KEY (`id`),\n";
        $out .= "  UNIQUE KEY `uq_cgph` (`id_client_group`, `id_file_state`),\n";
        $out .= "  CONSTRAINT `fk_cgph_client_group` FOREIGN KEY (`id_client_group`) REFERENCES `client_group` (`id`) ON DELETE CASCADE\n";
        $out .= ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n\n";

        $out .= "-- company.id_client_group + file_state.requires_payment_voucher\n";
        $out .= "ALTER TABLE `company` ADD COLUMN `id_client_group` BIGINT NULL AFTER `id`;\n";
        $out .= "CREATE INDEX `idx_company_client_group` ON `company` (`id_client_group`);\n";
        $out .= "ALTER TABLE `file_state` ADD COLUMN `requires_payment_voucher` TINYINT(1) NOT NULL DEFAULT 0 AFTER `enabled`;\n\n";

        // Forward-fix: legacy nexfile dump leaves these tables without
        // AUTO_INCREMENT (they relied on externally-assigned ids). The WIZARD
        // provisioning + the tenant operating going forward both need
        // auto-generated PKs to insert without specifying id every time.
        $out .= "ALTER TABLE `agency` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;\n\n";

        // FK integrity additions — el dump original deja muchas columnas id_*
        // sin FK declarada (proclive a huérfanos). Las agregamos aquí. Ver
        // `php spark tenant:audit-orphans --db <name>` para identificar y
        // limpiar huérfanos antes de aplicar estas FKs a un tenant ya creado.
        $out .= "-- ====== FK integrity additions ======\n";
        $out .= "-- Type-alignment (parents legacy INT, Phase A children BIGINT → downgrade):\n";
        $out .= "ALTER TABLE `client_group_phase` MODIFY `id_file_state` INT NOT NULL;\n";
        $out .= "ALTER TABLE `agency`             MODIFY `id_company`    INT DEFAULT NULL;\n\n";

        $out .= "-- Categoría A (Phase A, sin huérfanos):\n";
        $out .= "ALTER TABLE `client_group` ADD CONSTRAINT `fk_cg_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `client_group_process` ADD CONSTRAINT `fk_cgp_process` FOREIGN KEY (`id_process`) REFERENCES `process` (`id`) ON DELETE CASCADE;\n";
        $out .= "ALTER TABLE `client_group_phase` ADD CONSTRAINT `fk_cgph_file_state` FOREIGN KEY (`id_file_state`) REFERENCES `file_state` (`id`) ON DELETE CASCADE;\n";
        $out .= "ALTER TABLE `company` ADD CONSTRAINT `fk_company_client_group` FOREIGN KEY (`id_client_group`) REFERENCES `client_group` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n\n";

        $out .= "-- Categoría B (legacy hierarchy, post-cleanup):\n";
        $out .= "ALTER TABLE `agency` ADD CONSTRAINT `fk_agency_company` FOREIGN KEY (`id_company`) REFERENCES `company` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `document_type` ADD CONSTRAINT `fk_document_type_process_type` FOREIGN KEY (`id_process_type`) REFERENCES `process` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `document_type` ADD CONSTRAINT `fk_document_type_sub_process` FOREIGN KEY (`id_sub_process`) REFERENCES `process` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `liquidation_receipt_detail` ADD CONSTRAINT `fk_lrd_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `client_identification_data` ADD CONSTRAINT `fk_cid_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `config` ADD CONSTRAINT `fk_config_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n";
        $out .= "ALTER TABLE `payment_method` ADD CONSTRAINT `fk_payment_method_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;\n\n";

        // === Views (DEFINER stripped, source-DB refs rewritten to bare table refs) ===
        if ($views) {
            $out .= "-- ====== Views ======\n\n";
            foreach ($views as $v) {
                $ddl = $db->query("SHOW CREATE VIEW `{$sourceDb}`.`{$v}`")->getRowArray()['Create View'] ?? null;
                if (!$ddl) continue;
                // Strip DEFINER + SQL SECURITY
                $ddl = preg_replace('/DEFINER\s*=\s*`[^`]+`@`[^`]+`\s*/i', '', $ddl);
                $ddl = preg_replace('/SQL\s+SECURITY\s+DEFINER\s*/i', 'SQL SECURITY INVOKER ', $ddl);
                // Drop source-DB qualifier so view refs to its own DB
                $ddl = str_replace("`{$sourceDb}`.", '', $ddl);
                // Apply table renames inside view body
                foreach (self::TABLE_RENAMES as $from => $to) {
                    $ddl = preg_replace('/`' . preg_quote($from, '/') . '`/', "`{$to}`", $ddl);
                }
                $out .= "DROP VIEW IF EXISTS `{$v}`;\n";
                $out .= $ddl . ";\n\n";
            }
        }

        $out .= "SET FOREIGN_KEY_CHECKS = 1;\n";
        return $out;
    }

    private function buildDataSql($db, string $sourceDb): string
    {
        $out = "-- NexFile baseline catalog data dump\n";
        $out .= "-- Source: `{$sourceDb}` on " . date('Y-m-d H:i:s') . "\n";
        $out .= "-- Only catalog tables — no expedients, no clients, no transactional data.\n";
        $out .= "-- Generated by: php spark db:dump-baseline\n\n";
        $out .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

        foreach (self::CATALOG_TABLES as $t) {
            $targetTable = self::TABLE_RENAMES[$t] ?? $t;
            if (!$db->tableExists($t)) continue;
            $rows = $db->table($t)->orderBy('id', 'ASC')->get()->getResultArray();
            if (!$rows) continue;

            $out .= "-- ------ Data for `{$targetTable}` (" . count($rows) . " rows) ------\n";
            $out .= "TRUNCATE TABLE `{$targetTable}`;\n";

            // Determine column list from first row
            $cols = array_keys($rows[0]);
            $colsList = implode('`, `', $cols);

            // Special handling: file_state needs the new requires_payment_voucher column
            // pre-populated for backwards compat (Liquidación = id 2)
            $isFileState = ($targetTable === 'file_state');

            foreach ($rows as $r) {
                $values = [];
                foreach ($cols as $c) {
                    $v = $r[$c];
                    if ($v === null) $values[] = 'NULL';
                    elseif (is_numeric($v) && !preg_match('/^0\d/', $v)) $values[] = $v;
                    else $values[] = "'" . str_replace("'", "''", (string) $v) . "'";
                }
                if ($isFileState) {
                    // append the requires_payment_voucher column
                    $rpv = ((int) $r['id'] === 2) ? '1' : '0';
                    $colsForInsert = '`' . $colsList . '`, `requires_payment_voucher`';
                    $valuesForInsert = implode(', ', $values) . ', ' . $rpv;
                    $out .= "INSERT INTO `{$targetTable}` ({$colsForInsert}) VALUES ({$valuesForInsert});\n";
                } else {
                    $out .= "INSERT INTO `{$targetTable}` (`{$colsList}`) VALUES (" . implode(', ', $values) . ");\n";
                }
            }
            $out .= "\n";
        }

        $out .= "SET FOREIGN_KEY_CHECKS = 1;\n";
        return $out;
    }
}
