<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;

/**
 * Dumps the full schema + catalog data of a source DB (post-Tier 4 nexfile)
 * into two versioned SQL scripts:
 *
 *   DB/baseline/v1.0/schema.sql   ← CREATE TABLE / VIEW as-is from source
 *   DB/baseline/v1.0/data.sql     ← INSERT statements for catalog rows
 *
 * The source DB is expected to already carry all Tier 0b/2/3/4 renames and the
 * Phase A additions (client_group*, company.id_client_group, expedient_state
 * navigation flags, etc.). No on-the-fly transforms — the source is the truth.
 *
 * Stale legacy tables left in source (e.g. `process` after the Tier 3 rename
 * to `sale_type`) are filtered via SKIP_TABLES.
 *
 * Usage:
 *   php spark db:dump-baseline                          # source = default DB, version = 1.0
 *   php spark db:dump-baseline --source=nexfile --version=1.1
 */
class DumpBaselineCommand extends BaseCommand
{
    protected $group       = 'Tenant';
    protected $name        = 'db:dump-baseline';
    protected $description = 'Dump source DB schema + catalog data to DB/baseline/v<X>/{schema,data}.sql';
    protected $usage       = 'db:dump-baseline [--source=<db>] [--version=<v>]';
    protected $options     = [
        '--source'  => 'Source DB name (default: from .env)',
        '--version' => 'Baseline version label (default: 1.0)',
    ];

    /** Legacy tables left over in source DB that must NOT make it into the baseline.
     *  `process` was renamed to `sale_type` in Tier 3 but the original table was
     *  not dropped — it lingers with camelCase columns. */
    private const SKIP_TABLES = ['process'];

    /** Catalog tables whose rows go into data.sql. Order matters (FK deps).
     *  Names are POST-Tier 4 (current). Config tables (configuration_process,
     *  etc.) are NOT included — each tenant builds its own configuration. */
    private const CATALOG_TABLES = [
        'user_role',
        'sale_type',
        'customer_type',
        'operation_type',
        'payment_method',
        'expedient_state',
        'expedient_sub_state',
        'document_type',
        'expedient_reason',
        'document_error',
        'document_status',
        'expedient_exception_reason',
    ];

    public function run(array $params)
    {
        $sourceDb = (string) (CLI::getOption('source') ?? '');
        $version  = (string) (CLI::getOption('version') ?? '1.0');
        if (!preg_match('/^\d+\.\d+(\.\d+)?$/', $version)) {
            CLI::error('--version must be like 1.0 or 1.0.1');
            return EXIT_ERROR;
        }

        $db = Database::connect();
        if ($sourceDb === '') $sourceDb = $db->getDatabase();
        if (!preg_match('/^[A-Za-z0-9_]+$/', $sourceDb)) {
            CLI::error('invalid --source');
            return EXIT_ERROR;
        }

        $outDir = ROOTPATH . '../DB/baseline/v' . $version;
        if (!is_dir($outDir)) @mkdir($outDir, 0775, true);
        $schemaFile = $outDir . '/schema.sql';
        $dataFile   = $outDir . '/data.sql';

        CLI::write("Source DB: {$sourceDb}", 'cyan');
        CLI::write("Version  : {$version}", 'cyan');
        CLI::write("Output   : {$outDir}/", 'cyan');
        CLI::newLine();

        // ===== SCHEMA =====
        $schemaSql = $this->buildSchemaSql($db, $sourceDb);
        file_put_contents($schemaFile, $schemaSql);
        $kb = round(strlen($schemaSql) / 1024, 1);
        CLI::write("+ schema.sql ({$kb} KB)", 'green');

        // ===== DATA =====
        $dataSql = $this->buildDataSql($db, $sourceDb);
        file_put_contents($dataFile, $dataSql);
        $kb = round(strlen($dataSql) / 1024, 1);
        CLI::write("+ data.sql ({$kb} KB)", 'green');

        return EXIT_SUCCESS;
    }

    private function buildSchemaSql($db, string $sourceDb): string
    {
        $out = "-- NexFile baseline schema dump\n";
        $out .= "-- Source: `{$sourceDb}` on " . date('Y-m-d H:i:s') . "\n";
        $out .= "-- Source DB is expected to be post-Tier 4: renames already applied,\n";
        $out .= "-- Phase A tables present, FKs declared inline. Stale tables in\n";
        $out .= "-- SKIP_TABLES are omitted.\n";
        $out .= "-- Generated by: php spark db:dump-baseline\n\n";

        $out .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

        // Discover base tables vs views
        $rows = $db->query(
            "SELECT TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? ORDER BY TABLE_NAME",
            [$sourceDb]
        )->getResultArray();
        $baseTables = $views = [];
        foreach ($rows as $r) {
            if ($r['TABLE_TYPE'] === 'VIEW') $views[] = $r['TABLE_NAME'];
            else $baseTables[] = $r['TABLE_NAME'];
        }

        // === Base tables ===
        foreach ($baseTables as $t) {
            if (in_array($t, self::SKIP_TABLES, true)) continue;
            $ddl = $db->query("SHOW CREATE TABLE `{$sourceDb}`.`{$t}`")->getRowArray()['Create Table'] ?? null;
            if (!$ddl) continue;

            // Drop AUTO_INCREMENT=N counter (clean state for a new tenant)
            $ddl = preg_replace('/\s+AUTO_INCREMENT=\d+/', '', $ddl);

            $out .= "-- ------ Table: `{$t}` ------\n";
            $out .= "DROP TABLE IF EXISTS `{$t}`;\n";
            $out .= $ddl . ";\n\n";
        }

        // === Views (DEFINER stripped, source-DB refs rewritten to bare table refs) ===
        // Skip dead views: referencian tablas que no existen post-rename
        // (file, headerclient, orderbycar, etc.). Provision las saltaba y se
        // eliminaron del baseline en Tier 1 del refactor de naming.
        $deadViews = ['view_all_relations', 'view_client', 'view_files', 'view_files_by_client'];
        if ($views) {
            $out .= "-- ====== Views ======\n\n";
            foreach ($views as $v) {
                if (in_array($v, $deadViews, true)) continue;
                $ddl = $db->query("SHOW CREATE VIEW `{$sourceDb}`.`{$v}`")->getRowArray()['Create View'] ?? null;
                if (!$ddl) continue;
                // Strip DEFINER + SQL SECURITY
                $ddl = preg_replace('/DEFINER\s*=\s*`[^`]+`@`[^`]+`\s*/i', '', $ddl);
                $ddl = preg_replace('/SQL\s+SECURITY\s+DEFINER\s*/i', 'SQL SECURITY INVOKER ', $ddl);
                // Drop source-DB qualifier so view refs to its own DB
                $ddl = str_replace("`{$sourceDb}`.", '', $ddl);
                $out .= "DROP VIEW IF EXISTS `{$v}`;\n";
                $out .= $ddl . ";\n\n";
            }
        }

        $out .= "SET FOREIGN_KEY_CHECKS = 1;\n";
        return $out;
    }

    private function buildDataSql($db, string $sourceDb): string
    {
        $out = "-- NexFile baseline catalog data dump\n";
        $out .= "-- Source: `{$sourceDb}` on " . date('Y-m-d H:i:s') . "\n";
        $out .= "-- Only catalog tables — no expedients, no clients, no transactional data.\n";
        $out .= "-- Generated by: php spark db:dump-baseline\n\n";
        $out .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

        foreach (self::CATALOG_TABLES as $t) {
            if (!$db->tableExists($t)) continue;
            $rows = $db->table($t)->orderBy('id', 'ASC')->get()->getResultArray();
            if (!$rows) continue;

            $out .= "-- ------ Data for `{$t}` (" . count($rows) . " rows) ------\n";
            $out .= "TRUNCATE TABLE `{$t}`;\n";

            $cols = array_keys($rows[0]);
            $colsList = implode('`, `', $cols);

            foreach ($rows as $r) {
                $values = [];
                foreach ($cols as $c) {
                    $v = $r[$c];
                    if ($v === null) $values[] = 'NULL';
                    elseif (is_numeric($v) && !preg_match('/^0\d/', $v)) $values[] = $v;
                    else $values[] = "'" . str_replace("'", "''", (string) $v) . "'";
                }
                $out .= "INSERT INTO `{$t}` (`{$colsList}`) VALUES (" . implode(', ', $values) . ");\n";
            }
            $out .= "\n";
        }

        $out .= "SET FOREIGN_KEY_CHECKS = 1;\n";
        return $out;
    }
}
