-- NexFile baseline schema dump
-- Source: `nexfile_tenant_test8` on 2026-05-25 21:36:16
-- Source DB is expected to be post-Tier 4: renames already applied,
-- Phase A tables present, FKs declared inline. Stale tables in
-- SKIP_TABLES are omitted.
-- Generated by: php spark db:dump-baseline

SET FOREIGN_KEY_CHECKS = 0;

-- ------ Table: `activity_log` ------
DROP TABLE IF EXISTS `activity_log`;
CREATE TABLE `activity_log` (
  `id` int NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `id_user` int NOT NULL,
  `user_email` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `action` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `entity_type` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `entity_id` int NOT NULL,
  `entity_data` json DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_520_ci,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_520_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`id_user`),
  KEY `idx_action` (`action`),
  KEY `idx_entity_type` (`entity_type`),
  KEY `idx_entity_id` (`entity_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `FK_activity_log_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_activity_log_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `agency` ------
DROP TABLE IF EXISTS `agency`;
CREATE TABLE `agency` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '0',
  `id_agency_dms` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_company` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `FK_agency_IdLastUserUpdate` (`id_last_user_update`),
  KEY `fk_agency_company` (`id_company`),
  CONSTRAINT `fk_agency_company` FOREIGN KEY (`id_company`) REFERENCES `company` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_agency_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `agency_user` ------
DROP TABLE IF EXISTS `agency_user`;
CREATE TABLE `agency_user` (
  `id_user` bigint NOT NULL,
  `id_agency` bigint NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  KEY `WDIDX_Agency_User_IdUser` (`id_user`),
  KEY `WDIDX_Agency_User_IdAgency` (`id_agency`),
  KEY `WDIDX_Agency_User_IdAgency_IdUser` (`id_agency`,`id_user`),
  KEY `FK_agency_user_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `agency_user_ibfk_1` FOREIGN KEY (`id_agency`) REFERENCES `agency` (`id`),
  CONSTRAINT `agency_user_ibfk_2` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_agency_user_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `client` ------
DROP TABLE IF EXISTS `client`;
CREATE TABLE `client` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `last_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `mother_last_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `RFC` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `CURP` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `tel_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `tel_number2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `adviser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `business_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `agency_origin` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `client_type` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `RazonSocial` (`business_name`),
  KEY `WDIDX_Client_RFC` (`RFC`),
  KEY `FK_client_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_client_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `client_dms_relation` ------
DROP TABLE IF EXISTS `client_dms_relation`;
CREATE TABLE `client_dms_relation` (
  `id` int NOT NULL,
  `id_dms` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `id_agency` bigint DEFAULT NULL,
  `id_client_header` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `WDIDX_Client_Total_Relation_IdTotalDealer` (`id_dms`),
  KEY `WDIDX_Client_Total_Relation_IdAgency` (`id_agency`),
  KEY `WDIDX_Client_Total_Relation_idHeaderClient` (`id_client_header`),
  KEY `WDIDX_Client_Total_Relation_IdTotalDealerIdAgency` (`id_dms`,`id_agency`),
  KEY `FK_client_dms_relation_IdLastUserUpdate` (`id_last_user_update`),
  KEY `idx_client_dms_relation_idHeaderClient_IdAgency` (`id_client_header`,`id_agency`),
  CONSTRAINT `client_dms_relation_ibfk_1` FOREIGN KEY (`id_agency`) REFERENCES `agency` (`id`),
  CONSTRAINT `client_dms_relation_ibfk_2` FOREIGN KEY (`id_client_header`) REFERENCES `client_header` (`id`),
  CONSTRAINT `FK_client_dms_relation_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_CTR_Agency` FOREIGN KEY (`id_agency`) REFERENCES `agency` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_CTR_HeaderClient` FOREIGN KEY (`id_client_header`) REFERENCES `client_header` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `client_group` ------
DROP TABLE IF EXISTS `client_group`;
CREATE TABLE `client_group` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `registration_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_last_user_update` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_client_group_name` (`name`),
  KEY `fk_cg_last_user_update` (`id_last_user_update`),
  CONSTRAINT `fk_cg_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `client_group_phase` ------
DROP TABLE IF EXISTS `client_group_phase`;
CREATE TABLE `client_group_phase` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `id_client_group` bigint NOT NULL,
  `id_expedient_state` int NOT NULL,
  `display_order` int DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '1',
  `registration_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cgph` (`id_client_group`,`id_expedient_state`),
  KEY `fk_cgph_expedient_state` (`id_expedient_state`),
  CONSTRAINT `fk_cgph_client_group` FOREIGN KEY (`id_client_group`) REFERENCES `client_group` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cgph_expedient_state` FOREIGN KEY (`id_expedient_state`) REFERENCES `expedient_state` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `client_group_sale_type` ------
DROP TABLE IF EXISTS `client_group_sale_type`;
CREATE TABLE `client_group_sale_type` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `id_client_group` bigint NOT NULL,
  `id_sale_type` bigint NOT NULL,
  `display_order` int DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '1',
  `registration_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cgp` (`id_client_group`,`id_sale_type`),
  KEY `fk_cgst_sale_type` (`id_sale_type`),
  CONSTRAINT `fk_cgp_client_group` FOREIGN KEY (`id_client_group`) REFERENCES `client_group` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cgst_sale_type` FOREIGN KEY (`id_sale_type`) REFERENCES `sale_type` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `client_header` ------
DROP TABLE IF EXISTS `client_header`;
CREATE TABLE `client_header` (
  `id` bigint NOT NULL,
  `id_client` bigint DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `WDIDX_HeaderClient_IdClient` (`id_client`),
  KEY `FK_client_header_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `client_header_ibfk_1` FOREIGN KEY (`id_client`) REFERENCES `client` (`id`),
  CONSTRAINT `FK_client_header_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `client_identification_data` ------
DROP TABLE IF EXISTS `client_identification_data`;
CREATE TABLE `client_identification_data` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `id_client` bigint NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mother_last_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `business_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rfc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `curp` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tel_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tel_number2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `street` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `external_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `internal_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `neighborhood` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postal_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `municipality` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `country` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `birth_country` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nationality_country` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issuing_authority` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `incorporation_date` date DEFAULT NULL,
  `business_activity` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_last_user_update` bigint DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_id_client` (`id_client`),
  KEY `fk_cid_last_user_update` (`id_last_user_update`),
  CONSTRAINT `fk_cid_client` FOREIGN KEY (`id_client`) REFERENCES `client` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_cid_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `company` ------
DROP TABLE IF EXISTS `company`;
CREATE TABLE `company` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_client_group` bigint DEFAULT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `agency_connection` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `FK_company_IdLastUserUpdate` (`id_last_user_update`),
  KEY `idx_company_client_group` (`id_client_group`),
  CONSTRAINT `fk_company_client_group` FOREIGN KEY (`id_client_group`) REFERENCES `client_group` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_company_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `config` ------
DROP TABLE IF EXISTS `config`;
CREATE TABLE `config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `config_key` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `config_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `category` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sensitive` tinyint DEFAULT '0',
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_key` (`config_key`),
  KEY `idx_config_category` (`category`),
  KEY `fk_config_last_user_update` (`id_last_user_update`),
  CONSTRAINT `fk_config_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `configuration_process` ------
DROP TABLE IF EXISTS `configuration_process`;
CREATE TABLE `configuration_process` (
  `id` bigint NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `enabled` tinyint DEFAULT '0',
  `id_last_user_update` bigint DEFAULT '0',
  `id_customer_type` bigint DEFAULT '0',
  `id_operation_type` bigint DEFAULT '0',
  `id_agency` bigint DEFAULT '0',
  `id_sale_type` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_Config_Unique` (`id_sale_type`,`id_agency`,`id_customer_type`,`id_operation_type`),
  KEY `WDIDX_ConfigurationProcess_IdCustomerType` (`id_customer_type`),
  KEY `WDIDX_ConfigurationProcess_IdOperationType` (`id_operation_type`),
  KEY `WDIDX_ConfigurationProcess_IdAgency` (`id_agency`),
  KEY `WDIDX_ConfigurationProcess_IdProcess` (`id_sale_type`),
  KEY `WDIDX_ConfigProc_IdProcIdAgencyIdOpIdCust` (`id_sale_type`,`id_agency`,`id_operation_type`,`id_customer_type`),
  KEY `FK_configuration_process_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_Config_Agency` FOREIGN KEY (`id_agency`) REFERENCES `agency` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_Config_CustomerType` FOREIGN KEY (`id_customer_type`) REFERENCES `customer_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_Config_OperationType` FOREIGN KEY (`id_operation_type`) REFERENCES `operation_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_Config_Process` FOREIGN KEY (`id_sale_type`) REFERENCES `sale_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `FK_configuration_process_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `configuration_process_document_type` ------
DROP TABLE IF EXISTS `configuration_process_document_type`;
CREATE TABLE `configuration_process_document_type` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_document_type` bigint NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `id_configuration_process` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `WDIDX_ConfigurationProcess_DocumentType_IdDocumentType` (`id_document_type`),
  KEY `WDIDX_ConfigurationProcess_DocumentType_IdConfigurationProcess` (`id_configuration_process`),
  KEY `WDIDX_ConfigurationProcess_DocumentType_IdConfigurationProc00001` (`id_configuration_process`,`id_document_type`),
  KEY `FK_configuration_process_document_type_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `configuration_process_document_type_ibfk_1` FOREIGN KEY (`id_configuration_process`) REFERENCES `configuration_process` (`id`),
  CONSTRAINT `configuration_process_document_type_ibfk_2` FOREIGN KEY (`id_document_type`) REFERENCES `document_type` (`id`),
  CONSTRAINT `FK_configuration_process_document_type_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `customer_type` ------
DROP TABLE IF EXISTS `customer_type`;
CREATE TABLE `customer_type` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `FK_customer_type_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_customer_type_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `document_error` ------
DROP TABLE IF EXISTS `document_error`;
CREATE TABLE `document_error` (
  `id` int NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Id` (`id`),
  KEY `FK_document_file_error_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_document_file_error_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `document_status` ------
DROP TABLE IF EXISTS `document_status`;
CREATE TABLE `document_status` (
  `id` int NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Id` (`id`),
  KEY `FK_document_file_status_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_document_file_status_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `document_type` ------
DROP TABLE IF EXISTS `document_type`;
CREATE TABLE `document_type` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `enabled` tinyint DEFAULT '0',
  `id_last_user_update` bigint DEFAULT '0',
  `req_expiration` tinyint DEFAULT '0',
  `id_sale_type` bigint DEFAULT NULL,
  `required` tinyint DEFAULT '1',
  `id_sub_sale_type` bigint DEFAULT NULL,
  `document_auto_upload` tinyint DEFAULT '1',
  `available_to_client` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `WDIDX_DocumentType_IdIdProcessType` (`id`,`id_sale_type`),
  KEY `WDIDX_DocumentType_IdProcessTypeIdSubProcess` (`id_sale_type`,`id_sub_sale_type`),
  KEY `FK_document_type_IdLastUserUpdate` (`id_last_user_update`),
  KEY `fk_document_type_sub_sale_type` (`id_sub_sale_type`),
  CONSTRAINT `FK_document_type_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_document_type_sale_type` FOREIGN KEY (`id_sale_type`) REFERENCES `sale_type` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_document_type_sub_sale_type` FOREIGN KEY (`id_sub_sale_type`) REFERENCES `sale_type` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedient` ------
DROP TABLE IF EXISTS `expedient`;
CREATE TABLE `expedient` (
  `id` bigint NOT NULL,
  `id_client` bigint DEFAULT NULL,
  `id_order` bigint DEFAULT NULL,
  `id_customer_type` bigint DEFAULT NULL,
  `id_operation` bigint DEFAULT '0',
  `id_sale_type` bigint DEFAULT '0',
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_agency` bigint DEFAULT NULL,
  `id_seller` bigint DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_current_expedient_state` int DEFAULT '0',
  `id_order_total` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `attention_date` date DEFAULT NULL,
  `close_date` date DEFAULT NULL,
  `agend_hour` time DEFAULT NULL,
  `agend_date` date DEFAULT NULL,
  `id_inventory` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `WDIDX_File_IdClient` (`id_client`),
  KEY `WDIDX_File_IdOrder` (`id_order`),
  KEY `WDIDX_File_IdCustomerType` (`id_customer_type`),
  KEY `WDIDX_File_IdOperation` (`id_operation`),
  KEY `WDIDX_File_IdProcess` (`id_sale_type`),
  KEY `WDIDX_File_IdAgency` (`id_agency`),
  KEY `WDIDX_File_IdSeller` (`id_seller`),
  KEY `WDIDX_File_IdCurrentState` (`id_current_expedient_state`),
  KEY `WDIDX_File_IdOrderTotal` (`id_order_total`),
  KEY `WDIDX_File_IdInventary` (`id_inventory`),
  KEY `WDIDX_File_IdOrderTotalIdAgency` (`id_order_total`,`id_agency`),
  KEY `WDIDX_File_IdIdCurrentState` (`id`,`id_current_expedient_state`),
  KEY `IDX_File_RegistrationDate_IdAgency` (`registration_date`,`id_agency`),
  KEY `IDX_File_RegistrationDate_IdAgency_IdCurrentState` (`registration_date`,`id_agency`,`id_current_expedient_state`),
  KEY `IDX_File_RegistrationDate_idSeller` (`registration_date`,`id_seller`),
  KEY `IDX_File_RegistrationDate_IdAgency_idSeller` (`registration_date`,`id_agency`,`id_seller`),
  KEY `IDX_File_CloseDate` (`close_date`),
  KEY `IDX_File_RegistrationDate_CloseDate` (`registration_date`,`close_date`),
  KEY `IDX_File_Agency_State_Date` (`id_agency`,`id_current_expedient_state`,`registration_date` DESC),
  KEY `IDX_File_Client_Process` (`id_client`,`id_sale_type`),
  KEY `IDX_File_Client_Agency_State` (`id_client`,`id_agency`,`id_current_expedient_state`),
  KEY `IDX_File_OrderTotal` (`id_order_total`),
  KEY `IDX_File_Date_State` (`registration_date` DESC,`id_current_expedient_state`),
  KEY `FK_expedient_IdLastUserUpdate` (`id_last_user_update`),
  KEY `idx_expedient_RegistrationDate` (`registration_date` DESC),
  CONSTRAINT `expedient_ibfk_3` FOREIGN KEY (`id_operation`) REFERENCES `operation_type` (`id`),
  CONSTRAINT `expedient_ibfk_4` FOREIGN KEY (`id_customer_type`) REFERENCES `customer_type` (`id`),
  CONSTRAINT `expedient_ibfk_5` FOREIGN KEY (`id_sale_type`) REFERENCES `sale_type` (`id`),
  CONSTRAINT `expedient_ibfk_6` FOREIGN KEY (`id_agency`) REFERENCES `agency` (`id`),
  CONSTRAINT `expedient_ibfk_7` FOREIGN KEY (`id_seller`) REFERENCES `user` (`id`),
  CONSTRAINT `expedient_ibfk_8` FOREIGN KEY (`id_current_expedient_state`) REFERENCES `file_status` (`id`),
  CONSTRAINT `FK_expedient_IdClient` FOREIGN KEY (`id_client`) REFERENCES `client_header` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_expedient_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_expedient_IdOrder` FOREIGN KEY (`id_order`) REFERENCES `order` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_File_CustomerType` FOREIGN KEY (`id_customer_type`) REFERENCES `customer_type` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedient_document` ------
DROP TABLE IF EXISTS `expedient_document`;
CREATE TABLE `expedient_document` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `comment` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `expiration_date` timestamp NULL DEFAULT NULL,
  `path_document` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `enabled` tinyint DEFAULT '0',
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `id_expedient` bigint DEFAULT NULL,
  `id_validation` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_document_type` bigint DEFAULT NULL,
  `id_current_document_status` int DEFAULT NULL,
  `id_document_error` int DEFAULT NULL,
  `server_path` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_document_container` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `WDIDX_DocumentByFile_IdFile` (`id_expedient`),
  KEY `WDIDX_DocumentByFile_IdDocumentType` (`id_document_type`),
  KEY `WDIDX_DocumentByFile_IdCurrentStatus` (`id_current_document_status`),
  KEY `WDIDX_DocumentByFile_IdDocumentError` (`id_document_error`),
  KEY `IDX_DocumentByFile_File_Status` (`id_expedient`,`id_current_document_status`),
  KEY `IDX_DocumentByFile_Type_Status` (`id_document_type`,`id_current_document_status`),
  KEY `IDX_DocumentByFile_File_Type` (`id_expedient`,`id_document_type`),
  KEY `FK_file_document_IdLastUserUpdate` (`id_last_user_update`),
  KEY `idx_file_document_ExpirationDate` (`expiration_date`),
  KEY `idx_file_document_Enabled` (`enabled`),
  CONSTRAINT `expedient_document_ibfk_2` FOREIGN KEY (`id_document_type`) REFERENCES `document_type` (`id`),
  CONSTRAINT `expedient_document_ibfk_3` FOREIGN KEY (`id_current_document_status`) REFERENCES `document_status` (`id`),
  CONSTRAINT `expedient_document_ibfk_4` FOREIGN KEY (`id_document_error`) REFERENCES `document_error` (`id`),
  CONSTRAINT `FK_file_document_IdFile` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_file_document_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedient_exception_reason` ------
DROP TABLE IF EXISTS `expedient_exception_reason`;
CREATE TABLE `expedient_exception_reason` (
  `id` int NOT NULL,
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_type_reason` int DEFAULT NULL,
  `enabled` tinyint DEFAULT '1',
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `WDIDX_File_Extraordinary_Reasons_IdExtraordinaryType` (`id_type_reason`),
  KEY `FK_file_exception_reason_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_file_exception_reason_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedient_pld` ------
DROP TABLE IF EXISTS `expedient_pld`;
CREATE TABLE `expedient_pld` (
  `id` bigint NOT NULL,
  `id_expedient` bigint DEFAULT NULL,
  `privacy_notice_delivered` tinyint(1) DEFAULT '0' COMMENT '1=Yes, 0=No',
  `privacy_notice_date` datetime DEFAULT NULL COMMENT 'Delivery/acceptance date',
  `privacy_notice_method` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL COMMENT 'In-person, Digital, Mail, Miniportal',
  `privacy_notice_signature` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL COMMENT 'Path or reference to digital signature',
  `requires_beneficial_owner` tinyint(1) DEFAULT '0' COMMENT '1=Applies, 0=Not applicable',
  `beneficial_owner_captured` tinyint(1) DEFAULT '0' COMMENT '1=Yes, 0=Pending',
  `beneficial_owner_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `beneficial_owner_rfc` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `beneficial_owner_curp` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `beneficial_owner_percentage` decimal(5,2) DEFAULT NULL COMMENT 'Participation percentage',
  `beneficial_owner_capture_date` datetime DEFAULT NULL,
  `funds_source_captured` tinyint(1) DEFAULT '0' COMMENT '1=Yes, 0=Pending',
  `funds_source_description` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL COMMENT 'Description of funds origin',
  `funds_source_capture_date` datetime DEFAULT NULL,
  `identification_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL COMMENT 'CIF, CSF or NULL if not applicable',
  `geolocation_captured` tinyint(1) DEFAULT '0' COMMENT '1=Yes, 0=No',
  `geolocation_latitude` decimal(10,8) DEFAULT NULL,
  `geolocation_longitude` decimal(11,8) DEFAULT NULL,
  `geolocation_date` datetime DEFAULT NULL,
  `geolocation_origin` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL COMMENT 'Miniportal, App, Agency',
  `expedient_pld_complete` tinyint(1) DEFAULT '0' COMMENT '1=Complete, 0=Incomplete',
  `expedient_pld_complete_date` datetime DEFAULT NULL COMMENT 'When it was marked complete',
  `registration_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_last_user_update` bigint DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_pld_idfile` (`id_expedient`),
  KEY `idx_file_pld_completo` (`expedient_pld_complete`),
  KEY `idx_file_pld_aviso` (`privacy_notice_delivered`),
  KEY `idx_file_pld_beneficiario` (`beneficial_owner_captured`),
  KEY `FK_file_pld_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_file_pld_IdFile` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_file_pld_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci COMMENT='Datos PLD/AML por expediente - Ley Antilavado';

-- ------ Table: `expedient_pld_approved_document` ------
DROP TABLE IF EXISTS `expedient_pld_approved_document`;
CREATE TABLE `expedient_pld_approved_document` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `id_expedient_document` bigint NOT NULL,
  `id_expedient` bigint NOT NULL,
  `approved_by_client` tinyint(1) DEFAULT '1' COMMENT '1=Approved by client',
  `approval_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_approved_doc_iddocumentbyfile` (`id_expedient_document`),
  KEY `idx_approved_doc_idfile` (`id_expedient`),
  CONSTRAINT `fk_approved_doc_documentbyfile` FOREIGN KEY (`id_expedient_document`) REFERENCES `expedient_document` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_approved_doc_file` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Documents approved by client in Miniportal - cannot be modified';

-- ------ Table: `expedient_pld_beneficial_owner` ------
DROP TABLE IF EXISTS `expedient_pld_beneficial_owner`;
CREATE TABLE `expedient_pld_beneficial_owner` (
  `id` bigint NOT NULL,
  `id_expedient` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  `RFC` varchar(13) DEFAULT NULL,
  `CURP` varchar(18) DEFAULT NULL,
  `participation_percentage` decimal(5,2) DEFAULT NULL,
  `registration_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_beneficiario_idfile` (`id_expedient`),
  KEY `FK_file_pld_beneficial_owner_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `fk_beneficiario_file` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_file_pld_beneficial_owner_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ------ Table: `expedient_pld_geo_log` ------
DROP TABLE IF EXISTS `expedient_pld_geo_log`;
CREATE TABLE `expedient_pld_geo_log` (
  `id` bigint NOT NULL,
  `id_expedient` bigint NOT NULL,
  `latitude` decimal(10,8) NOT NULL,
  `longitude` decimal(11,8) NOT NULL,
  `action` varchar(100) DEFAULT NULL COMMENT 'Accept notice, Upload document, Sign',
  `origin` varchar(50) DEFAULT NULL COMMENT 'Miniportal, App',
  `registration_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_geolog_idfile` (`id_expedient`),
  KEY `FK_file_pld_geo_log_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_file_pld_geo_log_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_geolog_file` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ------ Table: `expedient_reason` ------
DROP TABLE IF EXISTS `expedient_reason`;
CREATE TABLE `expedient_reason` (
  `id` int NOT NULL,
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_type_reason` int DEFAULT NULL,
  `enabled` tinyint DEFAULT '1',
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_file_reasons_enabled` (`enabled`),
  KEY `idx_file_reasons_registration_date` (`registration_date`),
  KEY `idx_file_reasons_update_date` (`update_date`),
  KEY `idx_file_reasons_last_user_update` (`id_last_user_update`),
  CONSTRAINT `FK_file_reasons_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedient_share_token` ------
DROP TABLE IF EXISTS `expedient_share_token`;
CREATE TABLE `expedient_share_token` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `id_expedient` bigint NOT NULL,
  `token` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration_date` timestamp NULL DEFAULT NULL,
  `enabled` tinyint DEFAULT '1',
  `registration_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `id_last_user_update` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_share_token_token` (`token`),
  UNIQUE KEY `uk_share_token_idfile` (`id_expedient`),
  KEY `idx_share_token_enabled` (`enabled`),
  KEY `FK_file_share_token_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_file_share_token_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_share_token_file` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Token único por expediente para acceso al Miniportal';

-- ------ Table: `expedient_state` ------
DROP TABLE IF EXISTS `expedient_state`;
CREATE TABLE `expedient_state` (
  `id` int NOT NULL,
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  `requires_payment_voucher` tinyint(1) NOT NULL DEFAULT '0',
  `is_navigable` tinyint(1) NOT NULL DEFAULT '1',
  `allows_document_upload` tinyint(1) NOT NULL DEFAULT '0',
  `is_terminal` tinyint(1) NOT NULL DEFAULT '0',
  `is_system` tinyint(1) NOT NULL DEFAULT '0',
  `display_order` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Id` (`id`),
  KEY `FK_file_status_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_file_status_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedient_sub_state` ------
DROP TABLE IF EXISTS `expedient_sub_state`;
CREATE TABLE `expedient_sub_state` (
  `id` bigint NOT NULL,
  `id_expedient_state` int DEFAULT NULL,
  `name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `IDX_file_sub_status_IdFileStatus` (`id_expedient_state`),
  KEY `FK_file_sub_status_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_file_sub_status_file_status` FOREIGN KEY (`id_expedient_state`) REFERENCES `file_status` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `FK_file_sub_status_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `expedients_to_correct` ------
DROP TABLE IF EXISTS `expedients_to_correct`;
CREATE TABLE `expedients_to_correct` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `id_expedient` int unsigned NOT NULL,
  `id_agency` int unsigned NOT NULL,
  `nd_dms` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `api_result` json DEFAULT NULL COMMENT 'Respuesta del API (success, error, etc.)',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_expediente` (`id_expedient`),
  KEY `idx_agency` (`id_agency`),
  KEY `idx_ndDMS` (`nd_dms`),
  KEY `FK_files_to_correct_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_files_to_correct_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `factories` ------
DROP TABLE IF EXISTS `factories`;
CREATE TABLE `factories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(31) NOT NULL,
  `uid` varchar(31) NOT NULL,
  `class` varchar(63) NOT NULL,
  `icon` varchar(31) NOT NULL,
  `summary` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`),
  KEY `uid` (`uid`),
  KEY `deleted_at_id` (`deleted_at`,`id`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ------ Table: `liquidation_receipt_detail` ------
DROP TABLE IF EXISTS `liquidation_receipt_detail`;
CREATE TABLE `liquidation_receipt_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `id_expedient_document` bigint NOT NULL,
  `id_expedient` bigint NOT NULL,
  `amount` decimal(15,2) NOT NULL,
  `id_payment_method` bigint NOT NULL,
  `payment_date` date DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_document` (`id_expedient_document`),
  KEY `id_file` (`id_expedient`),
  KEY `id_payment_method` (`id_payment_method`),
  KEY `fk_lrd_last_user_update` (`id_last_user_update`),
  CONSTRAINT `fk_lrd_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `liquidation_receipt_detail_ibfk_1` FOREIGN KEY (`id_expedient_document`) REFERENCES `expedient_document` (`id`),
  CONSTRAINT `liquidation_receipt_detail_ibfk_2` FOREIGN KEY (`id_expedient`) REFERENCES `expedient` (`id`),
  CONSTRAINT `liquidation_receipt_detail_ibfk_3` FOREIGN KEY (`id_payment_method`) REFERENCES `payment_method` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `migrations` ------
DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `class` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `group` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `namespace` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `time` int NOT NULL,
  `batch` int unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `operation_type` ------
DROP TABLE IF EXISTS `operation_type`;
CREATE TABLE `operation_type` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `FK_operation_type_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_operation_type_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `order` ------
DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  `id` bigint NOT NULL,
  `number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `car_type` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `year` int DEFAULT '0',
  `vin` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint(1) DEFAULT '1',
  `model` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `advisor` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_dms` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_agency` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `amount` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `WDIDX_OrderByCar_IdTotalDealer` (`id_dms`),
  KEY `FK_order_IdLastUserUpdate` (`id_last_user_update`),
  KEY `idx_order_IdDMS_idagency_RegistrationDate` (`id_dms`,`id_agency`,`registration_date` DESC),
  CONSTRAINT `FK_order_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `payment_method` ------
DROP TABLE IF EXISTS `payment_method`;
CREATE TABLE `payment_method` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_payment_method_name` (`name`),
  KEY `fk_payment_method_last_user_update` (`id_last_user_update`),
  CONSTRAINT `fk_payment_method_last_user_update` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `sale_type` ------
DROP TABLE IF EXISTS `sale_type`;
CREATE TABLE `sale_type` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `enabled` tinyint DEFAULT '0',
  `registration_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `update_date` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `FK_process_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_process_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `sale_type_user` ------
DROP TABLE IF EXISTS `sale_type_user`;
CREATE TABLE `sale_type_user` (
  `id_user` bigint NOT NULL,
  `id_sale_type` bigint NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  KEY `WDIDX_Process_User_IdUser` (`id_user`),
  KEY `WDIDX_Process_User_IdProcess` (`id_sale_type`),
  KEY `WDIDX_Process_User_IdProcess_IdUser` (`id_sale_type`,`id_user`),
  KEY `FK_process_user_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_process_user_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `sale_type_user_ibfk_1` FOREIGN KEY (`id_sale_type`) REFERENCES `sale_type` (`id`),
  CONSTRAINT `sale_type_user_ibfk_2` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `user` ------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `enabled` tinyint DEFAULT '0',
  `id_user_role` bigint DEFAULT '0',
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `username` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pass` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `email` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `id_user_total` bigint DEFAULT '0',
  `default_agency` bigint DEFAULT '0',
  `user_pass` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `password_migrated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Flag para indicar si la contrase?a ya fue migrada a hash',
  `profile_image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci,
  `image_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `image_size` int DEFAULT NULL,
  `last_login_at` datetime DEFAULT NULL COMMENT 'Fecha y hora del último ingreso al sistema',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `WDIDX_User_IdUserRol` (`id_user_role`),
  KEY `WDIDX_User_UserPass` (`username`,`pass`),
  KEY `FK_user_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_user_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `user_ibfk_1` FOREIGN KEY (`id_user_role`) REFERENCES `user_role` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ------ Table: `user_activity_logs` ------
DROP TABLE IF EXISTS `user_activity_logs`;
CREATE TABLE `user_activity_logs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT NULL,
  `enabled` tinyint DEFAULT '1',
  `user_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del usuario que realiz? la acci?n',
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nombre de usuario',
  `action` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Tipo de acci?n realizada',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Descripci?n detallada de la acci?n',
  `change_details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Detalles espec?ficos del cambio realizado',
  `ip_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Direcci?n IP del usuario',
  `user_agent` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'User Agent del navegador',
  `url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL de la acci?n',
  `method` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'M?todo HTTP utilizado',
  `request_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Datos de la petici?n (sanitizados)',
  `response_status` int DEFAULT NULL COMMENT 'C?digo de estado de la respuesta HTTP',
  `execution_time` float DEFAULT NULL COMMENT 'Tiempo de ejecuci?n en milisegundos',
  `created_at` datetime NOT NULL COMMENT 'Fecha y hora de creaci?n del log',
  `updated_at` datetime NOT NULL COMMENT 'Fecha y hora de ?ltima actualizaci?n',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_action` (`action`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_user_action` (`user_id`,`action`),
  KEY `idx_ip_address` (`ip_address`),
  KEY `FK_user_activity_logs_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_user_activity_logs_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Logs de actividad de usuarios en la plataforma';

-- ------ Table: `user_refresh_token` ------
DROP TABLE IF EXISTS `user_refresh_token`;
CREATE TABLE `user_refresh_token` (
  `id` int unsigned NOT NULL,
  `id_user` bigint NOT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `refresh_token` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration_date` timestamp NULL DEFAULT NULL,
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `update_date` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `IdUser` (`id_user`),
  KEY `idx_refresh_token` (`refresh_token`(255)),
  KEY `FK_user_refresh_token_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_user_refresh_token_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_user_refresh_token_user` FOREIGN KEY (`id_user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------ Table: `user_role` ------
DROP TABLE IF EXISTS `user_role`;
CREATE TABLE `user_role` (
  `id` bigint NOT NULL,
  `name` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `registration_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `id_last_user_update` bigint DEFAULT '0',
  `enabled` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `Name` (`name`),
  KEY `FK_user_role_IdLastUserUpdate` (`id_last_user_update`),
  CONSTRAINT `FK_user_role_IdLastUserUpdate` FOREIGN KEY (`id_last_user_update`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

-- ====== Views ======

DROP VIEW IF EXISTS `view_client_company_amount`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `view_client_company_amount` AS select `c`.`id` AS `idCliente`,`a`.`id_company` AS `idCompany`,year(`f`.`registration_date`) AS `anio`,sum(coalesce(`obc1`.`amount`,`obc2`.`amount`,0)) AS `totalMonto` from ((((`expedient` `f` join `client` `c` on((`f`.`id_client` = `c`.`id`))) join `agency` `a` on((`f`.`id_agency` = `a`.`id`))) left join `order` `obc1` on((`obc1`.`id` = `f`.`id_order`))) left join (select `obc2a`.`id_dms` AS `id_dms`,`obc2a`.`id_agency` AS `id_agency`,`obc2a`.`amount` AS `amount` from (`order` `obc2a` join (select `order`.`id_dms` AS `id_dms`,`order`.`id_agency` AS `id_agency`,max(coalesce(`order`.`registration_date`,'1900-01-01')) AS `MaxDate` from `order` group by `order`.`id_dms`,`order`.`id_agency`) `obc2b` on(((`obc2a`.`id_dms` = `obc2b`.`id_dms`) and (`obc2a`.`id_agency` = `obc2b`.`id_agency`) and (coalesce(`obc2a`.`registration_date`,'1900-01-01') = `obc2b`.`MaxDate`))))) `obc2` on(((`f`.`id_order` is null) and (`obc2`.`id_dms` = `f`.`id_order_total`) and (`obc2`.`id_agency` = `f`.`id_agency`)))) group by `c`.`id`,`a`.`id_company`,year(`f`.`registration_date`) having (sum(coalesce(`obc1`.`amount`,`obc2`.`amount`,0)) > 0);

DROP VIEW IF EXISTS `view_client_company_amount_6m`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `view_client_company_amount_6m` AS select `c`.`id` AS `idCliente`,`a`.`id_company` AS `idCompany`,sum(coalesce(`lrd`.`amount`,0)) AS `totalMonto` from ((((`expedient` `f` join `client` `c` on((`f`.`id_client` = `c`.`id`))) join `agency` `a` on((`f`.`id_agency` = `a`.`id`))) join `liquidation_receipt_detail` `lrd` on(((`lrd`.`id_expedient` = `f`.`id`) and (`lrd`.`id_payment_method` = 1)))) join `expedient_document` `fd` on(((`fd`.`id` = `lrd`.`id_expedient_document`) and (`fd`.`enabled` = 1)))) where (coalesce(`lrd`.`payment_date`,cast(`lrd`.`registration_date` as date),cast(`f`.`registration_date` as date)) >= (curdate() - interval 6 month)) group by `c`.`id`,`a`.`id_company` having (sum(coalesce(`lrd`.`amount`,0)) > 0);

DROP VIEW IF EXISTS `view_client_company_amount_6m_total`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `view_client_company_amount_6m_total` AS select `c`.`id` AS `idCliente`,`a`.`id_company` AS `idCompany`,sum(coalesce(`lrd`.`amount`,0)) AS `totalMonto` from ((((`expedient` `f` join `client` `c` on((`f`.`id_client` = `c`.`id`))) join `agency` `a` on((`f`.`id_agency` = `a`.`id`))) join `liquidation_receipt_detail` `lrd` on((`lrd`.`id_expedient` = `f`.`id`))) join `expedient_document` `fd` on(((`fd`.`id` = `lrd`.`id_expedient_document`) and (`fd`.`enabled` = 1)))) where (coalesce(`lrd`.`payment_date`,cast(`lrd`.`registration_date` as date),cast(`f`.`registration_date` as date)) >= (curdate() - interval 6 month)) group by `c`.`id`,`a`.`id_company` having (sum(coalesce(`lrd`.`amount`,0)) > 0);

DROP VIEW IF EXISTS `view_client_relations`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `view_client_relations` AS select `hc`.`id_client` AS `idCliente`,coalesce(`ctr`.`id_dms`,'') AS `ndCliente`,trim(concat(coalesce(`c`.`name`,''),' ',coalesce(`c`.`last_name`,''),' ',coalesce(`c`.`mother_last_name`,''))) AS `cliente`,`hc`.`id` AS `IdClientHeader`,`c`.`name` AS `nombre`,`c`.`last_name` AS `apellidoPaterno`,`c`.`mother_last_name` AS `apellidoMaterno`,`c`.`RFC` AS `rfc`,`c`.`email` AS `email`,`c`.`tel_number` AS `telefono`,`c`.`tel_number2` AS `telefono2`,`c`.`business_name` AS `razonSocial`,`c`.`CURP` AS `curp`,`c`.`client_type` AS `tipoCliente`,`c`.`adviser` AS `asesor`,`c`.`agency_origin` AS `agenciaOrigen`,`c`.`registration_date` AS `fechaRegistro`,`c`.`update_date` AS `fechaActualizacion`,`ctr`.`id_agency` AS `id_agency` from ((`client_header` `hc` join `client_dms_relation` `ctr` on((`hc`.`id` = `ctr`.`id_client_header`))) join `client` `c` on((`c`.`id` = `hc`.`id_client`)));

DROP VIEW IF EXISTS `view_document_name`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `view_document_name` AS select `fd`.`id` AS `IdFileDocument`,`fd`.`id_expedient` AS `id_expedient`,coalesce(`dt`.`name`,`fd`.`name`) AS `file_name_original` from (`expedient_document` `fd` left join `document_type` `dt` on((`fd`.`id_document_type` = `dt`.`id`))) where (`fd`.`enabled` = 1);

SET FOREIGN_KEY_CHECKS = 1;
